### ISSUE TITLE
Requestor does not validate input parameter: client-id

### ISSUE THREAD

**Issue by tomaszmrugalski** [DamianManelski/dibbler-v-1.2#14]
I typed the following:

```
#./dibbler-requestor -i eth0 -dstaddr 2001:db8::100  -bulk -m CLIENT_ID input-parameters-are-not-validated-at-all
```

And requestor claimed to do:

```
2014.10.29 20:29:41 Requestor Debug     Creating ClientId-based query. Asking for input-parameters-are-not-validated-at-all ClientId.
```

Here's what actually was sent (see attached image)
![blq-query-by-client-id](https://cloud.githubusercontent.com/assets/663576/4833426/9d586614-5fa4-11e4-9672-1d89b7004e59.png)

**Comment by DamianManelski** [comment]
Fixed in commit 46830dde75c8318cf055aa6610af7d4a64a222dc on windows and 26257b18ad5b7dee324a9c649761e80e0c4b55c7 on Linux
